### ISSUE TITLE
LDAPProvider url is 404'ing on install.

### ISSUE THREAD

**Issue by sahaq** [YunoHost-Apps/mediawiki_ynh#25]
Attempting to install Mediawiki on a fresh install of Yunohost results in a 404 on the following URL; https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_31-7f81741.tar.gz

It appears that the file was removed, and an updated file placed at the same location; https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_31-8e93a3e.tar.gz

Updating the URL in the install script should resolve the current inability to do clean installs.  I'm not sure of a clean method of determining the current 'live' URL.

**Comment by ayes-web** [comment]
The file seems to have changed to https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_31-098cd58.tar.gz now, the sha256 sum for it is 653536b22c2dce57426c5b517f0b07647642fb0f3dc1f72f9efd43ab7dbce1a1
