### ISSUE TITLE
VisualEditor not working: found a solution

### ISSUE THREAD

**Issue by stampf** [YunoHost-Apps/mediawiki_ynh#34]
On a VPS where yunohost has been installed on top of vanilla debian, installed the yunohost mediawiki app and added 
`wfLoadExtension( 'VisualEditor' );`
at the end of LocalSettings.php
When editing a page with the editor, there's a popup error 500 with a trace in error.log of nginx:

`2021/03/02 12:35:59 [error] 895#895: *15627 could not find named location "@rewrite", client: fe80::a800:ff:feb2:9773, server: adaptationradicale.org, request: "GET /wiki/rest.php/adaptationradicale.org/v3/page/html/Accueil/20?redirect=false&stash=true HTTP/2.0", host: "adaptationradicale.org"`

In the mediawiki.conf file (inside nginx's directory), there's this line which seems to cause problems because the destination @rewrite doesn't exist (inside the PHP location part):
`try_files $uri @rewrite;`
I justed commented out, restarted nginx, and things seem to work properly now (VisualEditor is working)

**Comment by Salamandar** [comment]
Thanks for the info. I'm adding a fix.

**Comment by Salamandar** [comment]
Should be fixed !
