### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by boistordu** [YunoHost-Apps/mediawiki_ynh#36]
> 2021-05-08 03:37:52,127: DEBUG - + test -e /opt/yunohost-apps-src/mediawiki/ldap_provider.tar.gz
> 2021-05-08 03:37:52,127: DEBUG - ++ wget --tries 3 --no-dns-cache --timeout 900 --no-verbose --output-document=ldap_provider.tar.gz https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_35-ca854c1.tar.gz
> 2021-05-08 03:37:52,629: DEBUG - + out='https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_35-ca854c1.tar.gz:
> 2021-05-08 03:37:52,630: WARNING - https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_35-ca854c1.tar.gz:
> 2021-05-08 03:37:52,630: DEBUG - 2021-05-08 03:37:52 erreur 404 : Not Found.'
> 2021-05-08 03:37:52,631: WARNING - 2021-05-08 03:37:52 erreur 404 : Not Found.
> 2021-05-08 03:37:52,631: DEBUG - + ynh_die '--message=https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_35-ca854c1.tar.gz:
> 2021-05-08 03:37:52,632: DEBUG - 2021-05-08 03:37:52 erreur 404 : Not Found.'
> 2021-05-08 03:37:52,633: DEBUG - 2021-05-08 03:37:52 erreur 404 : Not Found.'
> 2021-05-08 03:37:52,634: DEBUG - + ret_code=1
> 2021-05-08 03:37:52,634: DEBUG - + echo 'https://extdist.wmflabs.org/dist/extensions/LDAPProvider-REL1_35-ca854c1.tar.gz:
> 2021-05-08 03:37:52,634: DEBUG - 2021-05-08 03:37:52 erreur 404 : Not Found.'
> 2021-05-08 03:37:52,634: DEBUG - + exit 1
> 2021-05-08 03:37:52,635: DEBUG - + ynh_exit_properly
> 2021-05-08 03:37:52,635: DEBUG - + local exit_code=1
> 2021-05-08 03:37:52,635: DEBUG - + '[' 1 -eq 0 ']'
> 2021-05-08 03:37:52,635: DEBUG - + trap '' EXIT
> 2021-05-08 03:37:52,636: DEBUG - + set +o errexit
> 2021-05-08 03:37:52,636: DEBUG - + set +o nounset
> 2021-05-08 03:37:52,636: DEBUG - + sleep 0.5
> 2021-05-08 03:37:53,138: DEBUG - + type -t ynh_clean_setup
> 2021-05-08 03:37:53,139: DEBUG - + ynh_clean_setup
> 2021-05-08 03:37:53,140: DEBUG - + true
> 2021-05-08 03:37:53,140: DEBUG - + exit 1
> 2021-05-08 03:37:53,177: ERROR - Unable to install mediawiki: An error occurred inside the app installation script

**Comment by Salamandar** [comment]
Hello, the issue should be resolved now.
