### ISSUE TITLE
Upgrade to Mediawiki 1.33.0

### ISSUE THREAD

**Issue by decentral1se** [YunoHost-Apps/mediawiki_ynh#4]
> https://lists.wikimedia.org/pipermail/mediawiki-announce/2019-July/000235.html

Do we expect any major issues? I might give it a try.

Thanks for packaging this!

**Comment by decentral1se** [comment]
Oh dear ....

> https://www.mediawiki.org/wiki/Release_notes/1.33#Upgrading_notes_for_1.33

**Comment by decentral1se** [comment]
Browsing https://www.mediawiki.org/wiki/Manual:Upgrading ...

**Comment by ashledombos** [comment]
Hello, what is the status of the devel branch? Couldn't it go master?

**Comment by decentral1se** [comment]
Hey @ashledombos, testing branch is working with a number of upgrades, please see https://github.com/YunoHost-Apps/mediawiki_ynh/pull/16 for the progress on merging this into master.

**Comment by Christophe31** [comment]
Not sure I should make a new issue for this but 1.33 is now EOL, so it should be upgraded again unless you want to skip 1.34 as 1.35 seems to be not so far.

**Comment by Salamandar** [comment]
Yes, I wanted to push to 1.34 but maybe 1.35 is even better.
I'm a bit worried about the upgrade because it supposes the user is on Debian 10 with php7.3.

**Comment by Christophe31** [comment]
I tryed installation this weekend, I got a 404 on the LDAP plugin download. So it may feel more urgent than it was. Do you have the node server which handle the wysiwyg of mediawiki in this setup?
