### ISSUE TITLE
Install fails with 404 Error on PluggableAuth-REL1_38-126bad8.tar.gz

### ISSUE THREAD

**Issue by franc00018** [YunoHost-Apps/mediawiki_ynh#79]
### Describe the bug

Error 404 while downloading this file: https://extdist.wmflabs.org/dist/extensions/PluggableAuth-REL1_38-126bad8.tar.gz

### Context

- Hardware: Dedicated hosting with Debian 11
- YunoHost version: 11.0.9.15
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

```bash
yunohost app install mediawiki
```

Options:

```
Choose the domain where this app should be installed []: 
Choose the URL path (after the domain) where this app should be installed: /
Should this app be exposed to anonymous visitors? [yes | no]: no
Choose the application language [fr | en]: fr
Choose an administrator user for this app []: 
Choose an administration password for this app: 
Choose the application name: YunoWiki
```

I get this error message. Some necessary file is not available

Warning: https://extdist.wmflabs.org/dist/extensions/PluggableAuth-REL1_38-126bad8.tar.gz:
Warning: 2022-11-14 05:27:12 ERROR 404: Not Found.

### Expected behavior

I expect the install script to complete successfully

### Logs

<https://paste.yunohost.org/raw/pumofuvahu>

**Comment by Salamandar** [comment]
*gasp* didnt see this issue… this is fixed now.
