### ISSUE TITLE
No email retrieved for the LDAP logged in user

### ISSUE THREAD

**Issue by decentral1se** [YunoHost-Apps/mediawiki_ynh#9]
May need https://www.mediawiki.org/wiki/Extension:LDAPUserInfo?

**Comment by decentral1se** [comment]
Possible to edit manually now with https://github.com/decentral1se/mediawiki_ynh/commit/da1a8227c18667d499e8ad77d55a57c6cf887a98.

**Comment by Salamandar** [comment]
Looks like LDAPUserInfo fixes the issue, but only for users that never connected before activation of the plugin (?).
I just have to add the correct version.

**Comment by Salamandar** [comment]
By the way, I can close that.
