### ISSUE TITLE
Installation fails at LDAPAuthentication2 extension due to file not found error.

### ISSUE THREAD

**Issue by GiHa** [YunoHost-Apps/mediawiki_ynh#95]
Installation fails at LDAPAuthentication2 extension due to file not found error.

```
2023-02-17 12:55:26,698: WARNING - Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
2023-02-17 12:55:26,698: WARNING - ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
2023-02-17 12:55:26,699: WARNING - https://extdist.wmflabs.org/dist/extensions/LDAPAuthentication2-REL1_39-b4c4283.tar.gz:
2023-02-17 12:55:26,700: WARNING - 2023-02-17 12:55:26 FEHLER 404: Not Found.
```

here is my full log: https://paste.yunohost.org/raw/oyuwifuzem

**Comment by pastorioo** [comment]
same error
https://paste.yunohost.org/raw/zetajaqoda

**Comment by vincent-lucy** [comment]
Thanks a lot @GiHa 

Actualization today :

`conf/ldap_authentication2.src:`

```
SOURCE_URL=https://extdist.wmflabs.org/dist/extensions/LDAPAuthentication2-REL1_39-2bea99f.tar.gz
SOURCE_SUM=ef069994e8e6e0450eab7003d85c25b66bda00309d3bb073eadd5fd588d29b68
SOURCE_SUM_PRG=sha256sum
SOURCE_FORMAT=tar.gz
SOURCE_IN_SUBDIR=false
SOURCE_FILENAME=
SOURCE_EXTRACT=true
```

**Comment by GiHa** [comment]
You welcome and thank you back!

Looks like we need some kind of automatisation here...

**Comment by GiHa** [comment]
> I have the same problem when updating:
> 
> https://paste.yunohost.org/raw/aqibigaquy

Of course... This is the same script...
There are no changes from Yunohost team. In opposite MediaWiki team changes the versions weekly if not daily so we still need to install it manually.
I have no idea if its possible to upgrade a official listed app with a custom script.
Probably this (https://forum.yunohost.org/t/yunohost-apps-upgrade-you-must-provide-a-url-to-upgrade-your-custom-app/3063) helps... 

P.S. I would encourage everyone to report this inconsistency to show that there is a need for action.

**Comment by Salamandar** [comment]
This should be fixed now :)
